name: nlp
channels:
  - defaults
dependencies:
  - absl-py=0.10.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - async_generator=1.10
  - attrs=20.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - cffi=1.14.3
  - colorama=0.4.3
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - google-pasta=0.2.0
  - graphviz=2.38
  - grpcio=1.31.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libpng=1.6.37
  - libprotobuf=3.13.0
  - libsodium=1.0.18
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.2.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - nbclient=0.5.0
  - nbconvert=6.0.7
  - nbformat=5.0.7
  - nest-asyncio=1.4.1
  - notebook=6.1.4
  - openssl=1.1.1h
  - opt_einsum=3.1.0
  - packaging=20.4
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pickleshare=0.7.5
  - pip=20.2.3
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - prompt_toolkit=3.0.7
  - protobuf=3.13.0
  - pycparser=2.20
  - pygments=2.7.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - python=3.6.2
  - python-dateutil=2.8.1
  - pywinpty=0.5.7
  - pyzmq=19.0.2
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - send2trash=1.5.0
  - setuptools=50.3.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - traitlets=4.3.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - astunparse==1.6.3
    - cachetools==4.1.1
    - chardet==3.0.4
    - contextlib2==0.6.0.post1
    - cycler==0.10.0
    - dill==0.3.2
    - future==0.18.2
    - gast==0.2.2
    - google-auth==1.22.1
    - google-auth-oauthlib==0.4.1
    - googleapis-common-protos==1.52.0
    - idna==2.10
    - imageio==2.9.0
    - joblib==0.17.0
    - kiwisolver==1.2.0
    - matplotlib==3.3.2
    - networkx==2.5
    - numpy==1.18.5
    - oauthlib==3.1.0
    - opencv-python==4.4.0.44
    - pillow==7.2.0
    - promise==2.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydot==1.4.1
    - pydotplus==2.0.2
    - pypiwin32==223
    - python-graphviz==0.14.1
    - pywavelets==1.1.1
    - pywin32==228
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-image==0.17.2
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - tensorboard==2.1.1
    - tensorboard-plugin-wit==1.7.0
    - tensorflow==2.1.0
    - tensorflow-addons==0.9.1
    - tensorflow-datasets==3.2.1
    - tensorflow-estimator==2.1.0
    - tensorflow-metadata==0.24.0
    - threadpoolctl==2.1.0
    - tifffile==2020.9.3
    - tornado==4.5.3
    - tqdm==4.50.0
    - typeguard==2.9.1
    - urllib3==1.25.10
prefix: C:\Users\ziaeeamir\AppData\Local\Continuum\anaconda3\envs\nlp

